<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>0.8.1.0</Version>
		<Authors>Xue-Remake</Authors>
		<ApplicationIcon>onxbg-3b1wn-001.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
	  <Content Include="onxbg-3b1wn-001.ico" />
	</ItemGroup>

</Project>
